### ISSUE TITLE
viewpagerAndroid is error in the reactnative0.61

### ISSUE THREAD

**Issue by cx5168** [ptomasroos/react-native-scrollable-tab-view#1061]
react: 16.9.0 => 16.9.0
react-native: 0.61.4 => 0.61.4

I have installed the react-native-viewpager as prompted, but I am getting an error.

![img_20191122](https://user-images.githubusercontent.com/29448456/69396942-68b80f00-0d27-11ea-8811-1b5d63e1d1e2.png)

**Comment by cx5168** [comment]
@ptomasroos 

react-native-scrollable-tab-view/index.js 
[const ViewPagerAndroid = require('@react-native-community/viewpager');]  is need comment.

**Comment by cx5168** [comment]
installed @react-native-community/viewpager.  solved it.

**Comment by brambang** [comment]
> installed @react-native-community/viewpager. solved it.

my problem is little bit different, because the message is 
[this.scrollview.setpage is not a function](url)

But when i check @react-native-community/viewpager in root node_modules or inside this library, is not existed.
soooo..
i tried installed in root node modules and inside this library, but still error (ver 3.3.0)
i tried NPM cache clean, same.

How to fix it?
What i found is this function is from @react-native-community/viewpager
